---
title: "Trabalho 1 - Demografia"
format: pdf
editor: visual
author: "Camila Mesquita, Laíse Ribeiro, Luísa Lopes, Nícolas Baldez"
---

```{r setup}
#| include: false
source("demog.R")
```

### **Questão 1: Diagrama de Lexis**

a\) Construir o Diagrama de Lexis para os dados de nascidos vivos de 2000 a 2024 da UF escolhida (SINASC) e de óbitos menores de 5 anos (idades simples) para o mesmo período segundo o ano de nascimento.

**Resposta:**

b\) Supondo população fechada (inexistência de migração), calcule a probabilidade de um recém-nascido na UF ou no território de escolha sobreviver à idade exata de 5 para as coortes de 2000 a 2019.

**Resposta:**

c\) Considerando o mesmo pressuposto, calcule a probabilidade de sobreviver ao primeiro aniversário dos recém-nascidos no período de 2000 a 2023.

**Resposta:**

d\) Para os anos de 2022 e 2023, calcule a probabilidade de morrer antes de completar o primeiro aniversário, segundo raça/cor (Desafio)

**Resposta:**

e\) Comente os valores encontrados. Não se esquecer da qualidade da informação trabalhada.

**Resposta:**

### **Questão 2: Natalidade/Fecundidade**

a\) Com base nos dados do SINASC, para cada um dos anos seguintes: 2010, 2019, 2021, 2022 e 2024, e na população por sexo e idade estimada (projetada), construa os seguintes indicadores para a Unidade da Federação (Use as projeções do IBGE - Revisão 2024) :

-   Taxa Bruta de Natalidade

-   Taxa Fecundidade Geral (TFG) e Taxas específicas de fecundidade - nfx (Grafique esses valores)

-   Taxa de Fecundidade Total (TFT) ou Índice Sintético de Fecundidade

-   Taxas específicas de fecundidade feminina (apenas os nascimentos femininos)

-   Taxa Bruta de Reprodução

-   Taxa Líquida de Reprodução (é necessária a informação da função L da Tábua de Vida)

**Resposta:**

b\) Obtenha todos os indicadores de 2022, considerando a população recenseada nesse ano.

**Resposta:**

c\) Comente esses resultados (inclusive os gráficos das nfx), fazendo referência a artigos já publicados sobre o assunto.

**Resposta:**

d\) Para os dados do SINASC para 2024, analise a associação entre (apresente ao menos uma medida de associação):

-   idade (em grupos de idade) e escolaridade da mãe (apresente a tabela de contingência e as frequências relativas)

-   tipo de parto e escolaridade da mãe (apresente a tabela de contingência e as frequências relativas)

Apresente graficamente os dados, obtenha medidas para essa associação e comente os resultados.

**Resposta:**

### **Questão 3: Mortalidade**

a\) Com base nos dados sobre óbitos do SIM para os anos: 2010, 2019, 2021, 2022 e 2024 e a população por sexo e idade estimada (projetada) para a UF ou território escolhido, obtenha os seguintes indicadores:

-   Taxa Bruta de Mortalidade

-   Taxas específicas de mortalidade por sexo e idade - nMx (grafique)

**Resposta:**

b\) Calcule a TMI, utilizando o **número médio de óbitos ocorridos entre 2022 e 2024 (numerador) e o número de nascimentos de 2023 (denominador**). Calcule os indicadores: taxa de mortalidade neonatal, neonatal precoce, neonatal tardia, posneonatal. A partir da informação sobre óbitos fetais dos mesmos anos, calcule a taxa de mortalidade perinatal.

**Resposta:**

c\) Compare a estrutura de mortalidade por causas entre 2010, 2021 e 2024. Utilize 20 grupos de causas mais frequentes, segundo os grupos do CID-10 (ver Tabnet - Datasus), por sexo, e grupos de idade (\<5; 5 a 14; 15-39; 40-59; 60 e +) para os anos selecionados. Comente os resultados. Destacar a mortalidade por Covid-19 (CID B34.2).

**Resposta:**

d\) Construa Tábuas de Vida para cada sexo para a UF escolhida para 2010 e 2024, a partir das taxas específicas de mortalidade obtidas no item a:

-   Utilize a TMI obtida no item b. Lembre-se de que deve-se obter a TMI para cada sexo em separado.

-   Estime os fatores de separação para cada sexo, nas idades 0-1 e 1-4, com base nos microdados do SIM.

-   Compare os valores da função de esperança de vida para as idades exatas 0 e 60 com os obtidos no estudo do IBGE (Projeções) e no estudo GBD. Comente os resultados obtidos e o significado desses indicadores.

-   Com base na TV calculada, grafique as funções lx e nqx para cada sexo e comente os resultados.

-   Comente os resultados à luz de artigos recém publicados.

**Resposta:**
